#!/bin/env python3
# Created by atbswp v0.3.0 (https://git.sr.ht/~rmpr/atbswp)
# on 06 Apr 2025 
import pyautogui
import os
import time
pyautogui.FAILSAFE = False

pyautogui.keyDown('winleft')
pyautogui.keyUp('winleft')
time.sleep(1)
#search in whisker menu
pyautogui.write('keep')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
time.sleep(3)
pyautogui.mouseDown(474, 54, 'left')
pyautogui.mouseUp(474, 54, 'left')
time.sleep(3)
pyautogui.write('spending')
time.sleep(1)
pyautogui.mouseDown(370, 265, 'left')
pyautogui.mouseUp(370, 265, 'left')
time.sleep(2)
pyautogui.mouseDown(511, 265, 'left')
pyautogui.mouseUp(511, 265, 'left')
pyautogui.mouseDown(512, 264, 'left')
pyautogui.mouseUp(512, 264, 'left')
time.sleep(1)
#select all
pyautogui.keyDown('ctrlleft');pyautogui.keyDown('a')
pyautogui.keyUp('a');pyautogui.keyUp('ctrlleft')
time.sleep(1)
#copy to clipboard
pyautogui.keyDown('ctrlleft');pyautogui.keyDown('c')
pyautogui.keyUp('c');pyautogui.keyUp('ctrlleft')

print('opening sms.txt')
import subprocess
subprocess.Popen(['geany', '/media/admin/New Volume/prog_stuff_calc/bank_expenses/sms.txt'])

time.sleep(1)
#select all
pyautogui.keyDown('ctrlleft');pyautogui.keyDown('a')
pyautogui.keyUp('a');pyautogui.keyUp('ctrlleft')
#replace with clipboard content
pyautogui.keyDown('ctrlleft');pyautogui.keyDown('v')
pyautogui.keyUp('v');pyautogui.keyUp('ctrlleft')
pyautogui.keyDown('ctrlleft');pyautogui.keyDown('s')
pyautogui.keyUp('s');pyautogui.keyUp('ctrlleft')

from tkinter import messagebox as mb
mb.showwarning(title = "Completed", message = "Fetched backup to text file")
